### ISSUE TITLE
how to use sweet-dropdown in mvc

### ISSUE THREAD

**Issue by nikosurya** [adeptoas/sweet-dropdown#3]
can you tell me how to use this dropdown in mvc. because i tried and it got error "function is not defined
    at HTMLAnchorElement.onclick". sorry if its not the issue of the sweet-dropdown but i hope you guys tell me how to do it. thanks.

btw i already ask this in stackoverflow but still getting no answer.

https://stackoverflow.com/questions/44251385/mvc-function-is-not-defined-at-onclick/

**Comment by bluefirex** [comment]
From your link I can see your question has been answered. Can you post your solution here, too, for future googlers?

**Comment by nikosurya** [comment]
ok, so the solution of my problem above is the comma in javascript i made.
javascript code
`function updateShift(empId)`
`{`
    `$.post('@Url.Action("updateShift","jadwal")',{empId:empId } function(data) {`
        `alert("suksess");`
    `})`
`}`

when i use the code it give me error `function is not defined
at HTMLAnchorElement.onclick`. to fix this just add `,` before `function(data){`

`function updateShift(empId)`
`{`
    `$.post('@Url.Action("updateShift","jadwal")',{empId:empId }, function(data) {`
        `alert("suksess");`
    `})`
`}`

and now when i click on the sweet-dropdown it detect the js and calling my controller.

the sweet-dropdown code
`<div class="dropdown-menu dropdown-anchor-top-left dropdown-has-anchor" id="data1">`
   ` <ul>`
        `@foreach(var shift in Model.ShiftModelList)`
        `{`    
            `<li><a onclick="updateShift('@item.EmployeeId')">@shift.ShiftId</a></li>`
        `}`
`</div>`
