### ISSUE TITLE
how to get the value ？

### ISSUE THREAD

**Issue by iHTCboy** [adeptoas/sweet-dropdown#7]
```
$(document).on("click", "#my_dropdown ul li", function (event) {
    var index = $(this).index();
    console.log(index);
});
```
how get the value?

if has `<li class="divider"></li>`

index will be : 0 2 4 6

divider can use css show, no't use li?

**Comment by bluefirex** [comment]
You don't get values from the dropdown itself because the dropdown could be anything. If you want to use callbacks, place them on individual items, like so:

```html
<li data-action="do-something">...</li>
```

```js
$('[data-action=do-something]').click(function(event) {
    // do something
});
```

If you need more values, you can pass them via data:

```html
<li data-action="do-something" data-some-value="123">...</li>
```

```js
$('[data-action=do-something]').click(function(event) {
  const someValue = $(this).data('some-value')
});
```
